#!/usr/bin/env python3
"""
Sync a bookmark-style HTML export into a local Markdown archive.

Primary goals:
- Preserve the HTML folder/category structure in Markdown.
- Detect new/changed/removed URLs across future HTML exports.
- Preserve existing per-URL descriptions and notes across syncs.
- Emit a pending-annotations template for URLs that still need explanation.

The script assumes a Netscape bookmark HTML structure such as the exports
generated by Chrome, Edge, Firefox, Raindrop import exports, etc.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import tempfile
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path
from typing import DefaultDict, Dict, Iterable, List, Optional, Sequence, Set, Tuple
from urllib.parse import urlparse, urlunparse


STATE_VERSION = 1
DEFAULT_EXTERNAL_STATE_BASE = Path.home() / ".codex" / "html-bookmarks-state"
HEAVY_HOST_THRESHOLD = 1000

ROOT_CATEGORIES = Path("01 Categories")
ROOT_LINKS = Path("02 Links")
ROOT_DOMAINS = Path("03 Domains")
ROOT_STATE = Path(".sync-state")
ROOT_REPORTS = Path("00 Reports")

DASHBOARD_FILE = "Dashboard.md"
NEW_LINKS_FILE = "New Links.md"
CHANGED_LINKS_FILE = "Changed Links.md"
REMOVED_LINKS_FILE = "Removed Links.md"
EXCLUDED_LINKS_FILE = "Excluded Links.md"
MANAGED_TOP_LEVEL_NAMES = {
    ROOT_REPORTS.name,
    ROOT_CATEGORIES.name,
    ROOT_LINKS.name,
    ROOT_DOMAINS.name,
    DASHBOARD_FILE,
}
LATEST_SUMMARY_FILE = "latest-summary.json"
PENDING_ANNOTATIONS_FILE = "pending_annotations.json"
EXCLUDED_LINKS_JSON = "excluded_links.json"
STATE_FILE = "state.json"


LANG_PACKS: Dict[str, Dict[str, str]] = {
    "zh": {
        "dashboard_title": "HTML 链接归档仪表盘",
        "new_links_title": "本次新增链接",
        "changed_links_title": "本次变更链接",
        "removed_links_title": "本次移除链接",
        "excluded_links_title": "已过滤噪音链接",
        "categories_title": "分类目录",
        "links_title": "链接索引",
        "domains_title": "域名索引",
        "stats_title": "统计",
        "label_layout": "渲染布局",
        "label_state_root": "同步状态目录",
        "status_active": "在库",
        "status_removed": "已移除",
        "label_total_bookmarks": "HTML 中书签条目数",
        "label_total_unique": "HTML 中唯一 URL 数",
        "label_active": "当前在库 URL 数",
        "label_categories": "分类节点数",
        "label_domains": "域名数",
        "label_new": "新增 URL",
        "label_changed": "变更 URL",
        "label_removed": "移除 URL",
        "label_excluded": "过滤 URL",
        "label_pending": "待补充说明",
        "label_last_sync": "最近同步时间",
        "label_source_html": "来源 HTML",
        "label_url": "网址",
        "label_domain": "域名",
        "label_status": "状态",
        "label_first_seen": "首次收录",
        "label_last_seen": "最近出现",
        "label_categories_short": "分类",
        "label_also_seen_as": "其他标题",
        "label_bookmark_count": "HTML 中出现次数",
        "label_bookmark_added": "书签添加时间",
        "label_tags": "标签",
        "label_entry_note": "详情页",
        "label_open_entry": "打开条目",
        "label_counts": "数量",
        "section_purpose": "作用说明",
        "section_note": "补充备注",
        "section_links": "链接",
        "section_subcategories": "子分类",
        "section_all_links": "全部链接",
        "section_category_paths": "分类路径",
        "section_recent_changes": "本次同步变化",
        "section_summary": "摘要",
        "section_annotations": "待补充说明",
        "section_domain_links": "该域名下的链接",
        "section_root_links": "未分类到子目录的链接",
        "section_direct_links": "当前分类下直接包含的链接",
        "section_principal_categories": "主分类概览",
        "section_meta": "元信息",
        "none": "(无)",
        "root_category": "(根目录)",
        "pending_description": "待补充说明。",
        "pending_note": "(无)",
        "empty_report": "本次没有相关条目。",
        "summary_all_good": "本次没有待补充说明的链接。",
        "summary_show_pending": "待补充说明模板",
        "label_summary_root": "分类摘要根路径",
        "section_shards": "分片",
    },
    "en": {
        "dashboard_title": "HTML Links Dashboard",
        "new_links_title": "New Links",
        "changed_links_title": "Changed Links",
        "removed_links_title": "Removed Links",
        "excluded_links_title": "Excluded Noise Links",
        "categories_title": "Categories",
        "links_title": "Links Index",
        "domains_title": "Domains",
        "stats_title": "Stats",
        "label_layout": "Layout",
        "label_state_root": "State root",
        "status_active": "Active",
        "status_removed": "Removed",
        "label_total_bookmarks": "Bookmark items in HTML",
        "label_total_unique": "Unique URLs in HTML",
        "label_active": "Active URLs",
        "label_categories": "Category nodes",
        "label_domains": "Domains",
        "label_new": "New URLs",
        "label_changed": "Changed URLs",
        "label_removed": "Removed URLs",
        "label_excluded": "Excluded URLs",
        "label_pending": "Pending descriptions",
        "label_last_sync": "Last sync",
        "label_source_html": "Source HTML",
        "label_url": "URL",
        "label_domain": "Domain",
        "label_status": "Status",
        "label_first_seen": "First seen",
        "label_last_seen": "Last seen",
        "label_categories_short": "Categories",
        "label_also_seen_as": "Alternate titles",
        "label_bookmark_count": "Occurrences in HTML",
        "label_bookmark_added": "Bookmark added at",
        "label_tags": "Tags",
        "label_entry_note": "Entry note",
        "label_open_entry": "Open entry",
        "label_counts": "Count",
        "section_purpose": "Purpose",
        "section_note": "Notes",
        "section_links": "Links",
        "section_subcategories": "Subcategories",
        "section_all_links": "All links",
        "section_category_paths": "Category paths",
        "section_recent_changes": "Changes in this sync",
        "section_summary": "Summary",
        "section_annotations": "Pending annotations",
        "section_domain_links": "Links in this domain",
        "section_root_links": "Links without a deeper category",
        "section_direct_links": "Links directly in this category",
        "section_principal_categories": "Principal categories",
        "section_meta": "Metadata",
        "none": "(none)",
        "root_category": "(root)",
        "pending_description": "Pending description.",
        "pending_note": "(none)",
        "empty_report": "No entries in this report.",
        "summary_all_good": "No links are waiting for descriptions.",
        "summary_show_pending": "Pending annotations template",
        "label_summary_root": "Summary root path",
        "section_shards": "Shards",
    },
}


ACTIVE_LANG = "zh"
I18N = LANG_PACKS[ACTIVE_LANG]


@dataclass
class BookmarkEntry:
    url: str
    title: str
    category_path: List[str]
    add_date: str
    last_modified: str


class BookmarkHTMLParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.entries: List[BookmarkEntry] = []
        self.folder_stack: List[str] = []
        self.dl_stack: List[bool] = []
        self.pending_folder: Optional[str] = None
        self.capture_tag: Optional[str] = None
        self.capture_attrs: Dict[str, str] = {}
        self.capture_text: List[str] = []

    def handle_starttag(self, tag: str, attrs: List[Tuple[str, Optional[str]]]) -> None:
        lower_tag = tag.lower()
        attr_map = {k.lower(): (v or "") for k, v in attrs}
        if lower_tag in {"a", "h3"}:
            self.capture_tag = lower_tag
            self.capture_attrs = attr_map
            self.capture_text = []
            return
        if lower_tag == "dl":
            opened_for_folder = self.pending_folder is not None
            if opened_for_folder:
                self.folder_stack.append(self.pending_folder or "")
                self.pending_folder = None
            self.dl_stack.append(opened_for_folder)

    def handle_endtag(self, tag: str) -> None:
        lower_tag = tag.lower()
        if lower_tag == "h3" and self.capture_tag == "h3":
            folder_name = clean_text("".join(self.capture_text))
            if folder_name:
                self.pending_folder = folder_name
            self.capture_tag = None
            self.capture_attrs = {}
            self.capture_text = []
            return
        if lower_tag == "a" and self.capture_tag == "a":
            raw_url = self.capture_attrs.get("href", "").strip()
            if raw_url:
                title = clean_text("".join(self.capture_text)) or title_from_url(raw_url)
                self.entries.append(
                    BookmarkEntry(
                        url=raw_url,
                        title=title,
                        category_path=list(self.folder_stack),
                        add_date=self.capture_attrs.get("add_date", "").strip(),
                        last_modified=self.capture_attrs.get("last_modified", "").strip(),
                    )
                )
            self.capture_tag = None
            self.capture_attrs = {}
            self.capture_text = []
            return
        if lower_tag == "dl" and self.dl_stack:
            opened_for_folder = self.dl_stack.pop()
            if opened_for_folder and self.folder_stack:
                self.folder_stack.pop()

    def handle_data(self, data: str) -> None:
        if self.capture_tag:
            self.capture_text.append(data)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Sync bookmark HTML into a Markdown archive.")
    parser.add_argument("--input-html", required=True, help="Path to bookmark HTML export")
    parser.add_argument(
        "--target-root",
        required=True,
        help="Root path where the archive folder should live; accepts absolute or relative paths",
    )
    parser.add_argument(
        "--layout",
        choices=["compact", "per-url"],
        default="compact",
        help="Rendering layout: compact reduces file count for Obsidian; per-url keeps one note per URL",
    )
    parser.add_argument(
        "--state-root",
        help="Optional directory for sync state files; compact layout defaults to an external path and uses an Obsidian-Documents sibling when targeting an Obsidian vault",
    )
    parser.add_argument(
        "--container-name",
        default="HTML Bookmarks",
        help="Folder name created under target root",
    )
    parser.add_argument(
        "--mode",
        choices=["merge", "create"],
        default="merge",
        help="merge preserves previous descriptions/history; create rebuilds from the HTML snapshot only",
    )
    parser.add_argument(
        "--missing-policy",
        choices=["keep", "remove"],
        default="keep",
        help="When merging, keep preserves prior links missing from the new HTML; remove treats the new HTML as a full snapshot",
    )
    parser.add_argument(
        "--title-language",
        choices=["zh", "en"],
        default="zh",
        help="Language for generated headings and placeholder text",
    )
    parser.add_argument(
        "--annotations-file",
        help="Optional JSON file with descriptions/notes to import before rendering",
    )
    parser.add_argument(
        "--summary-path",
        help="Optional path for copying the machine-readable summary JSON",
    )
    return parser.parse_args()


def set_active_language(lang: str) -> None:
    global ACTIVE_LANG, I18N
    if lang not in LANG_PACKS:
        raise ValueError(f"unsupported language: {lang}")
    ACTIVE_LANG = lang
    I18N = LANG_PACKS[lang]


def t(key: str) -> str:
    return I18N[key]


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def clean_text(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def short_hash(value: str, length: int = 8) -> str:
    return hashlib.sha1(value.encode("utf-8")).hexdigest()[:length]


def sanitize_filename(value: str, default: str = "item") -> str:
    cleaned = re.sub(r'[\\/:*?"<>|]+', " ", value)
    cleaned = clean_text(cleaned).strip(". ")
    return cleaned or default


def slugify(value: str, default: str = "item", max_length: int = 72) -> str:
    base = value.strip().lower()
    base = re.sub(r"https?://", "", base)
    base = re.sub(r"[^a-z0-9]+", "-", base)
    base = base.strip("-")
    if not base:
        base = default
    return base[:max_length].strip("-") or default


def normalize_url(raw_url: str) -> str:
    value = raw_url.strip()
    parsed = urlparse(value)
    if not parsed.scheme or not parsed.netloc:
        return value
    scheme = parsed.scheme.lower()
    hostname = (parsed.hostname or "").lower()
    port = parsed.port
    if port and not ((scheme == "http" and port == 80) or (scheme == "https" and port == 443)):
        netloc = f"{hostname}:{port}"
    else:
        netloc = hostname
    if parsed.username:
        auth = parsed.username
        if parsed.password:
            auth += f":{parsed.password}"
        netloc = f"{auth}@{netloc}"
    path = parsed.path or "/"
    if path != "/" and path.endswith("/"):
        path = path.rstrip("/")
    return urlunparse((scheme, netloc, path, "", parsed.query, parsed.fragment))


def host_from_url(url: str) -> str:
    parsed = urlparse(url)
    return (parsed.hostname or "unknown-host").lower()


def title_from_url(url: str) -> str:
    parsed = urlparse(url)
    path_parts = [part for part in parsed.path.split("/") if part]
    if path_parts:
        guess = path_parts[-1].replace("-", " ").replace("_", " ")
        guess = clean_text(guess)
        if guess:
            return guess
    if parsed.hostname:
        return parsed.hostname
    return url


def quote_yaml(value: object) -> str:
    raw = str(value)
    escaped = raw.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
    return f'"{escaped}"'


def format_inline_list(items: Sequence[str]) -> str:
    cleaned = [item for item in items if item]
    if not cleaned:
        return "[]"
    return "[" + ", ".join(quote_yaml(item) for item in cleaned) + "]"


def markdown_rel_path(from_file: Path, to_file: Path) -> str:
    rel = os.path.relpath(to_file, from_file.parent)
    return rel.replace(os.sep, "/")


def display_category_path(parts: Sequence[str]) -> str:
    if not parts:
        return t("root_category")
    return " / ".join(parts)


def display_timestamp(raw_value: str) -> str:
    if not raw_value:
        return t("none")
    if raw_value.isdigit():
        try:
            ts = int(raw_value)
            return datetime.fromtimestamp(ts, timezone.utc).replace(microsecond=0).isoformat()
        except (OverflowError, OSError, ValueError):
            return raw_value
    return raw_value


def load_json(path: Path) -> object:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def save_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
        handle.write("\n")


def default_external_state_root(archive_root: Path) -> Path:
    parts = archive_root.resolve().parts
    marker = ("Library", "Mobile Documents", "iCloud~md~obsidian", "Documents")
    for idx in range(len(parts) - len(marker) + 1):
        if parts[idx : idx + len(marker)] == marker:
            docs_root = Path(*parts[: idx + len(marker)])
            return docs_root / f"{archive_root.name}-state"
    key = short_hash(str(archive_root.resolve()), 12)
    return DEFAULT_EXTERNAL_STATE_BASE / key


def parse_bookmark_html(path: Path) -> List[BookmarkEntry]:
    parser = BookmarkHTMLParser()
    parser.feed(path.read_text(encoding="utf-8", errors="ignore"))
    parser.close()
    return parser.entries


def separator_like_title(title: str) -> bool:
    return bool(re.fullmatch(r"[═=─—_\-\s]{6,}", clean_text(title)))


def noise_reason_for_entry(entry: BookmarkEntry) -> Optional[str]:
    url = normalize_url(entry.url)
    parsed = urlparse(url)
    host = (parsed.hostname or "").lower()
    if parsed.scheme in {"chrome-extension", "javascript", "data", "about"}:
        return f"scheme:{parsed.scheme}"
    if host in {"separator.site", "separator.mayastudios.com"}:
        return f"host:{host}"
    if separator_like_title(entry.title):
        return "separator-title"
    return None


def noise_reason_for_record(url: str, title: str) -> Optional[str]:
    parsed = urlparse(normalize_url(url))
    host = (parsed.hostname or "").lower()
    if parsed.scheme in {"chrome-extension", "javascript", "data", "about"}:
        return f"scheme:{parsed.scheme}"
    if host in {"separator.site", "separator.mayastudios.com"}:
        return f"host:{host}"
    if separator_like_title(title):
        return "separator-title"
    return None


def split_noise_entries(
    entries: Sequence[BookmarkEntry],
) -> Tuple[List[BookmarkEntry], List[Tuple[BookmarkEntry, str]]]:
    clean_entries: List[BookmarkEntry] = []
    excluded_entries: List[Tuple[BookmarkEntry, str]] = []
    for entry in entries:
        reason = noise_reason_for_entry(entry)
        if reason:
            excluded_entries.append((entry, reason))
        else:
            clean_entries.append(entry)
    return clean_entries, excluded_entries


def pick_title(titles: Iterable[str], fallback: str) -> str:
    clean_titles = [clean_text(title) for title in titles if clean_text(title)]
    if not clean_titles:
        return fallback
    counts = Counter(clean_titles)
    ranked = sorted(counts.items(), key=lambda item: (-item[1], len(item[0]), item[0].lower()))
    return ranked[0][0]


def dedupe_strings(values: Iterable[str]) -> List[str]:
    seen: Set[str] = set()
    out: List[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        out.append(value)
    return out


def dedupe_paths(values: Iterable[Sequence[str]]) -> List[List[str]]:
    seen: Set[Tuple[str, ...]] = set()
    out: List[List[str]] = []
    for parts in values:
        key = tuple(parts)
        if key in seen:
            continue
        seen.add(key)
        out.append(list(parts))
    return sorted(out, key=lambda item: (len(item), [part.lower() for part in item]))


def aggregate_entries(entries: Sequence[BookmarkEntry]) -> Dict[str, Dict[str, object]]:
    grouped: Dict[str, Dict[str, object]] = {}
    for entry in entries:
        normalized = normalize_url(entry.url)
        bucket = grouped.setdefault(
            normalized,
            {
                "url": normalized,
                "raw_urls": [],
                "titles": [],
                "category_paths": [],
                "bookmark_count": 0,
                "bookmark_add_dates": [],
                "bookmark_last_modified_dates": [],
            },
        )
        bucket["raw_urls"].append(entry.url)
        bucket["titles"].append(entry.title)
        bucket["category_paths"].append(entry.category_path or [])
        bucket["bookmark_count"] = int(bucket["bookmark_count"]) + 1
        if entry.add_date:
            bucket["bookmark_add_dates"].append(entry.add_date)
        if entry.last_modified:
            bucket["bookmark_last_modified_dates"].append(entry.last_modified)

    records: Dict[str, Dict[str, object]] = {}
    for url, bucket in grouped.items():
        raw_titles = [str(value) for value in bucket["titles"]]
        title = pick_title(raw_titles, fallback=title_from_url(url))
        category_paths = dedupe_paths(bucket["category_paths"])
        if not category_paths:
            category_paths = [[]]
        bookmark_add_dates = dedupe_strings(sorted(str(value) for value in bucket["bookmark_add_dates"]))
        bookmark_last_modified_dates = dedupe_strings(
            sorted(str(value) for value in bucket["bookmark_last_modified_dates"])
        )
        records[url] = {
            "url": url,
            "host": host_from_url(url),
            "title": title,
            "titles": dedupe_strings(sorted(raw_titles)),
            "category_paths": category_paths,
            "bookmark_count": int(bucket["bookmark_count"]),
            "bookmark_add_dates": bookmark_add_dates,
            "bookmark_last_modified_dates": bookmark_last_modified_dates,
        }
    return records


def aggregate_excluded_entries(
    excluded_entries: Sequence[Tuple[BookmarkEntry, str]],
) -> Dict[str, Dict[str, object]]:
    aggregated = aggregate_entries([entry for entry, _ in excluded_entries])
    reasons: DefaultDict[str, Set[str]] = defaultdict(set)
    for entry, reason in excluded_entries:
        reasons[normalize_url(entry.url)].add(reason)
    for url, record in aggregated.items():
        record["filter_reasons"] = sorted(reasons.get(url, set()))
    return aggregated


def load_state(path: Path) -> Dict[str, object]:
    if not path.exists():
        return {"version": STATE_VERSION, "records": {}}
    payload = load_json(path)
    if not isinstance(payload, dict):
        raise ValueError(f"invalid state file: {path}")
    records = payload.get("records", {})
    if not isinstance(records, dict):
        raise ValueError(f"invalid records block in state file: {path}")
    return {"version": int(payload.get("version", STATE_VERSION)), "records": records}


def load_annotations(path: Optional[Path]) -> Dict[str, Dict[str, object]]:
    if path is None:
        return {}
    payload = load_json(path)
    out: Dict[str, Dict[str, object]] = {}
    if isinstance(payload, dict):
        iterable = [{"url": url, **(data if isinstance(data, dict) else {})} for url, data in payload.items()]
    elif isinstance(payload, list):
        iterable = [item for item in payload if isinstance(item, dict)]
    else:
        raise ValueError("annotations JSON must be an object or a list")
    for item in iterable:
        raw_url = clean_text(str(item.get("url", "")))
        if not raw_url:
            continue
        description = clean_text(str(item.get("description", "")))
        note = clean_text(str(item.get("note", "")))
        raw_tags = item.get("tags", [])
        tags: List[str] = []
        if isinstance(raw_tags, list):
            tags = [clean_text(str(tag)) for tag in raw_tags if clean_text(str(tag))]
        payload = {
            "description": description,
            "note": note,
            "tags": dedupe_strings(tags),
        }
        for url in {raw_url, normalize_url(raw_url)}:
            out[url] = payload
    return out


def source_fingerprint(record: Dict[str, object]) -> str:
    payload = {
        "title": record.get("title", ""),
        "titles": list(record.get("titles", [])),
        "category_paths": list(record.get("category_paths", [])),
        "bookmark_count": int(record.get("bookmark_count", 0)),
        "bookmark_add_dates": list(record.get("bookmark_add_dates", [])),
        "bookmark_last_modified_dates": list(record.get("bookmark_last_modified_dates", [])),
    }
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def merge_records(
    current_records: Dict[str, Dict[str, object]],
    previous_state: Dict[str, object],
    annotations: Dict[str, Dict[str, object]],
    source_html: Path,
    mode: str,
    missing_policy: str,
) -> Tuple[Dict[str, object], Dict[str, List[str]]]:
    previous_records = previous_state.get("records", {}) if mode == "merge" else {}
    if not isinstance(previous_records, dict):
        previous_records = {}

    timestamp = now_iso()
    merged: Dict[str, Dict[str, object]] = {}
    changes: Dict[str, List[str]] = {
        "new": [],
        "changed": [],
        "removed": [],
        "unchanged": [],
        "reactivated": [],
    }

    for url in sorted(current_records):
        current = dict(current_records[url])
        previous = previous_records.get(url) if isinstance(previous_records, dict) else None
        previous = previous if isinstance(previous, dict) else None
        annotation = annotations.get(url, {})
        description = clean_text(str(annotation.get("description") or (previous or {}).get("description", "")))
        note = clean_text(str(annotation.get("note") or (previous or {}).get("note", "")))
        existing_tags = previous.get("tags", []) if previous else []
        new_tags = annotation.get("tags", existing_tags)
        tags = dedupe_strings(str(tag) for tag in new_tags if clean_text(str(tag)))

        current["description"] = description
        current["note"] = note
        current["tags"] = tags
        current["status"] = "active"
        current["first_seen_at"] = (previous or {}).get("first_seen_at", timestamp)
        current["last_seen_at"] = timestamp
        current["removed_at"] = ""
        current["source_html"] = str(source_html)
        current["source_signature"] = source_fingerprint(current)

        if previous is None:
            changes["new"].append(url)
        else:
            prev_signature = str(previous.get("source_signature", ""))
            curr_signature = str(current["source_signature"])
            if previous.get("status") == "removed":
                changes["reactivated"].append(url)
                changes["changed"].append(url)
            elif prev_signature != curr_signature:
                changes["changed"].append(url)
            else:
                changes["unchanged"].append(url)
        merged[url] = current

    if mode == "merge":
        for url, previous in previous_records.items():
            if url in merged:
                continue
            if not isinstance(previous, dict):
                continue
            if noise_reason_for_record(str(previous.get("url", url)), str(previous.get("title", ""))):
                continue
            carried = dict(previous)
            if missing_policy == "keep":
                carried["status"] = "active"
                carried["removed_at"] = ""
                merged[url] = carried
                changes["unchanged"].append(url)
            else:
                if carried.get("status") != "removed":
                    carried["status"] = "removed"
                    carried["removed_at"] = timestamp
                    changes["removed"].append(url)
                merged[url] = carried

    state = {
        "version": STATE_VERSION,
        "last_sync_at": timestamp,
        "source_html": str(source_html),
        "records": merged,
    }
    return state, changes


def build_pending_annotations(records: Dict[str, Dict[str, object]]) -> List[Dict[str, object]]:
    pending: List[Dict[str, object]] = []
    for url in sorted(records):
        record = records[url]
        if record.get("status") != "active":
            continue
        if clean_text(str(record.get("description", ""))):
            continue
        pending.append(
            {
                "url": url,
                "title": str(record.get("title", "")),
                "host": str(record.get("host", "")),
                "category_paths": list(record.get("category_paths", [])),
                "description": "",
                "note": str(record.get("note", "")),
                "tags": list(record.get("tags", [])),
            }
        )
    return pending


def active_records(state: Dict[str, object]) -> Dict[str, Dict[str, object]]:
    raw = state.get("records", {})
    if not isinstance(raw, dict):
        return {}
    return {
        url: record
        for url, record in raw.items()
        if isinstance(record, dict) and record.get("status") == "active"
    }


def removed_records(state: Dict[str, object]) -> Dict[str, Dict[str, object]]:
    raw = state.get("records", {})
    if not isinstance(raw, dict):
        return {}
    return {
        url: record
        for url, record in raw.items()
        if isinstance(record, dict) and record.get("status") == "removed"
    }


def sort_records(records: Iterable[Dict[str, object]]) -> List[Dict[str, object]]:
    return sorted(
        records,
        key=lambda record: (
            str(record.get("title", "")).lower(),
            str(record.get("host", "")).lower(),
            str(record.get("url", "")).lower(),
        ),
    )


def link_note_rel_path(record: Dict[str, object]) -> Path:
    url = str(record.get("url", ""))
    parsed = urlparse(url)
    host = sanitize_filename(str(record.get("host", "unknown-host")), default="unknown-host")
    path_hint = "-".join(part for part in parsed.path.split("/") if part)
    if not path_hint:
        path_hint = parsed.fragment or "index"
    base = slugify(path_hint or str(record.get("title", "")), default="link")
    return ROOT_LINKS / host / f"{base}-{short_hash(url)}.md"


def domain_note_rel_path(host: str) -> Path:
    safe_host = sanitize_filename(host, default="unknown-host")
    return ROOT_DOMAINS / f"{safe_host}.md"


def build_category_tree(
    records: Dict[str, Dict[str, object]]
) -> Tuple[
    DefaultDict[Tuple[str, ...], Set[str]],
    DefaultDict[Tuple[str, ...], List[Dict[str, object]]],
    DefaultDict[Tuple[str, ...], Set[str]],
]:
    folder_children: DefaultDict[Tuple[str, ...], Set[str]] = defaultdict(set)
    folder_direct_links: DefaultDict[Tuple[str, ...], List[Dict[str, object]]] = defaultdict(list)
    folder_all_urls: DefaultDict[Tuple[str, ...], Set[str]] = defaultdict(set)
    folder_all_urls[tuple()] = set()

    for record in sort_records(records.values()):
        url = str(record.get("url", ""))
        category_paths = record.get("category_paths", [[]])
        if not isinstance(category_paths, list) or not category_paths:
            category_paths = [[]]
        for raw_parts in category_paths:
            parts = [clean_text(str(part)) for part in raw_parts if clean_text(str(part))]
            folder_direct_links[tuple(parts)].append(record)
            for depth in range(len(parts)):
                parent = tuple(parts[:depth])
                folder_children[parent].add(parts[depth])
            for depth in range(len(parts) + 1):
                folder_all_urls[tuple(parts[:depth])].add(url)
    return folder_children, folder_direct_links, folder_all_urls


def build_category_fs_map(
    folder_children: DefaultDict[Tuple[str, ...], Set[str]]
) -> Dict[Tuple[str, ...], Path]:
    mapping: Dict[Tuple[str, ...], Path] = {tuple(): ROOT_CATEGORIES}

    def visit(parent: Tuple[str, ...]) -> None:
        used: Dict[str, str] = {}
        for child in sorted(folder_children.get(parent, set()), key=lambda value: value.lower()):
            base = sanitize_filename(child, default="Category")
            candidate = base
            if candidate in used and used[candidate] != child:
                candidate = f"{base}-{short_hash(child, 6)}"
            used[candidate] = child
            child_key = parent + (child,)
            mapping[child_key] = mapping[parent] / candidate
            visit(child_key)

    visit(tuple())
    return mapping


def compact_top_category_rel_dir(top_key: Tuple[str, ...]) -> Path:
    return ROOT_CATEGORIES / sanitize_filename(top_key[-1], default="Category")


def compact_branch_note_rel_path(branch_key: Tuple[str, ...]) -> Path:
    top_dir = compact_top_category_rel_dir(branch_key[:3])
    if len(branch_key) <= 3:
        return top_dir / "Overview.md"
    slug = sanitize_filename(branch_key[-1], default="Branch")
    return top_dir / f"{slug}-{short_hash(display_category_path(branch_key), 6)}.md"


def collect_compact_category_branches(
    records: Dict[str, Dict[str, object]],
    summary_root: Tuple[str, ...],
) -> Dict[Tuple[str, ...], Set[Tuple[str, ...]]]:
    branches: DefaultDict[Tuple[str, ...], Set[Tuple[str, ...]]] = defaultdict(set)
    for record in records.values():
        if record.get("status") != "active":
            continue
        for parts in record.get("category_paths", [[]]):
            clean_parts = tuple(str(part) for part in parts)
            if len(clean_parts) < len(summary_root) + 1:
                continue
            top_key = clean_parts[: len(summary_root) + 1]
            branch_key = clean_parts[: len(summary_root) + 2] if len(clean_parts) >= len(summary_root) + 2 else top_key
            branches[top_key].add(branch_key)
    return dict(branches)


def render_bulleted_paths(paths: Sequence[Sequence[str]]) -> str:
    if not paths:
        return f"- {t('root_category')}\n"
    lines = []
    for parts in paths:
        lines.append(f"- `{display_category_path(parts)}`")
    return "\n".join(lines) + "\n"


def render_tags(tags: Sequence[str]) -> str:
    cleaned = [tag for tag in tags if tag]
    if not cleaned:
        return t("none")
    return ", ".join(f"`{tag}`" for tag in cleaned)


def collapse_summary_root(
    folder_children: DefaultDict[Tuple[str, ...], Set[str]]
) -> Tuple[str, ...]:
    current: Tuple[str, ...] = tuple()
    while True:
        children = sorted(folder_children.get(current, set()), key=str.lower)
        if len(children) != 1:
            return current
        current = current + (children[0],)


def principal_categories(
    summary_root: Tuple[str, ...],
    folder_children: DefaultDict[Tuple[str, ...], Set[str]],
    folder_all_urls: DefaultDict[Tuple[str, ...], Set[str]],
    limit: int = 30,
) -> List[Dict[str, object]]:
    items: List[Dict[str, object]] = []
    for child in sorted(folder_children.get(summary_root, set()), key=str.lower):
        child_key = summary_root + (child,)
        items.append(
            {
                "name": child,
                "count": len(folder_all_urls.get(child_key, set())),
                "path": list(child_key),
            }
        )
    items.sort(key=lambda item: (-int(item["count"]), str(item["name"]).lower()))
    return items[:limit]


def render_link_summary_line(
    record: Dict[str, object],
    heading_level: int = 3,
    from_file: Optional[Path] = None,
    note_path: Optional[Path] = None,
    include_domain: bool = True,
    include_categories: bool = True,
) -> str:
    title = str(record.get("title", "Untitled"))
    description = clean_text(str(record.get("description", ""))) or t("pending_description")
    categories = "; ".join(display_category_path(parts) for parts in record.get("category_paths", [[]]))
    heading_prefix = "#" * max(1, min(6, heading_level))
    lines = [
        f"{heading_prefix} {title}",
        "",
        f"- {t('label_url')}: [{record.get('url', '')}]({record.get('url', '')})",
        f"- {t('section_purpose')}: {description}",
    ]
    if include_domain:
        lines.insert(3, f"- {t('label_domain')}: `{record.get('host', '')}`")
    if include_categories:
        insert_at = 4 if include_domain else 3
        lines.insert(insert_at, f"- {t('label_categories_short')}: {categories}")
    if from_file is not None and note_path is not None:
        rel = markdown_rel_path(from_file, note_path)
        lines.append(f"- {t('label_entry_note')}: [{t('label_open_entry')}]({rel})")
    note = clean_text(str(record.get("note", "")))
    if note:
        lines.append(f"- {t('section_note')}: {note}")
    return "\n".join(lines)


def shard_key_for_value(value: str) -> str:
    cleaned = clean_text(value)
    if not cleaned:
        return "other"
    first = cleaned[0].lower()
    if first.isdigit():
        return "0-9"
    if "a" <= first <= "z":
        return first
    return "other"


def shard_key_for_host(value: str) -> str:
    cleaned = clean_text(value).lower()
    if cleaned.startswith("www."):
        cleaned = cleaned[4:]
    token = "".join(ch for ch in cleaned if ch.isalnum())
    if not token:
        return "other"
    if token[0].isdigit():
        return "0-9"
    if len(token) >= 2 and token[0].isalpha() and token[1].isalpha():
        return f"{token[0]}{token[1]}"
    if token[0].isalpha():
        return token[0]
    return "other"


def shard_sort_key(key: str) -> Tuple[int, str]:
    if key == "0-9":
        return (0, key)
    if len(key) == 1 and key.isalpha():
        return (1, key)
    return (2, key)


def shard_display_name(key: str) -> str:
    return key.upper() if len(key) == 1 and key.isalpha() else key


def link_shard_rel_path(key: str) -> Path:
    return ROOT_LINKS / f"{sanitize_filename(key, default='other')}.md"


def domain_shard_rel_path(key: str) -> Path:
    return ROOT_DOMAINS / f"{sanitize_filename(key, default='other')}.md"


def heavy_host_dir_rel_path(host: str) -> Path:
    return ROOT_LINKS / "_hosts" / f"{slugify(host, default='host')}-{short_hash(host, 6)}"


def heavy_host_shard_rel_path(host: str, key: str) -> Path:
    return heavy_host_dir_rel_path(host) / f"{sanitize_filename(key, default='other')}.md"


def host_detail_shard_key(record: Dict[str, object]) -> str:
    url = str(record.get("url", ""))
    parsed = urlparse(url)
    parts = [part for part in parsed.path.split("/") if part]
    token_source = parts[0] if parts else str(record.get("title", ""))
    token = "".join(ch for ch in clean_text(token_source).lower() if ch.isalnum())
    if not token:
        return "other"
    if token[0].isdigit():
        return "0-9"
    if len(token) >= 2 and token[0].isalpha() and token[1].isalpha():
        return f"{token[0]}{token[1]}"
    if token[0].isalpha():
        return token[0]
    return "other"


def build_link_shards(
    records: Dict[str, Dict[str, object]]
) -> Tuple[Dict[str, List[Dict[str, object]]], Dict[str, Dict[str, List[Dict[str, object]]]]]:
    host_groups: DefaultDict[str, List[Dict[str, object]]] = defaultdict(list)
    for record in sort_records(records.values()):
        host_groups[str(record.get("host", "unknown-host"))].append(record)

    general_shards: DefaultDict[str, List[Dict[str, object]]] = defaultdict(list)
    heavy_host_shards: Dict[str, Dict[str, List[Dict[str, object]]]] = {}

    for host, host_records in host_groups.items():
        if len(host_records) >= HEAVY_HOST_THRESHOLD:
            subshards: DefaultDict[str, List[Dict[str, object]]] = defaultdict(list)
            for record in host_records:
                subshards[host_detail_shard_key(record)].append(record)
            heavy_host_shards[host] = {
                key: sort_records(items) for key, items in sorted(subshards.items(), key=lambda item: shard_sort_key(item[0]))
            }
        else:
            general_shards[shard_key_for_host(host)].extend(host_records)

    return (
        {key: sort_records(items) for key, items in sorted(general_shards.items(), key=lambda item: shard_sort_key(item[0]))},
        heavy_host_shards,
    )


def build_domain_shards(
    domain_groups: Dict[str, List[Dict[str, object]]]
) -> Dict[str, List[Tuple[str, List[Dict[str, object]]]]]:
    shards: DefaultDict[str, List[Tuple[str, List[Dict[str, object]]]]] = defaultdict(list)
    for host, records in domain_groups.items():
        key = shard_key_for_value(host)
        shards[key].append((host, sort_records(records)))
    for key in shards:
        shards[key].sort(key=lambda item: item[0].lower())
    return dict(shards)


def render_link_note(record: Dict[str, object]) -> str:
    title = str(record.get("title", title_from_url(str(record.get("url", "")))))
    description = clean_text(str(record.get("description", ""))) or t("pending_description")
    note = clean_text(str(record.get("note", ""))) or t("pending_note")
    tags = [str(tag) for tag in record.get("tags", [])]
    category_paths = record.get("category_paths", [[]])
    titles = [str(item) for item in record.get("titles", []) if str(item) != title]

    lines = [
        "---",
        f"title: {quote_yaml(title)}",
        f"url: {quote_yaml(record.get('url', ''))}",
        f"host: {quote_yaml(record.get('host', ''))}",
        f"status: {quote_yaml(t('status_active'))}",
        f"first_seen_at: {quote_yaml(record.get('first_seen_at', ''))}",
        f"last_seen_at: {quote_yaml(record.get('last_seen_at', ''))}",
        f"category_paths: {format_inline_list(display_category_path(parts) for parts in category_paths)}",
        f"tags: {format_inline_list(tags)}",
        "---",
        "",
        f"# {title}",
        "",
        f"- {t('label_url')}: [{record.get('url', '')}]({record.get('url', '')})",
        f"- {t('label_domain')}: `{record.get('host', '')}`",
        f"- {t('label_status')}: {t('status_active')}",
        f"- {t('label_first_seen')}: {record.get('first_seen_at', '')}",
        f"- {t('label_last_seen')}: {record.get('last_seen_at', '')}",
        f"- {t('label_bookmark_count')}: {record.get('bookmark_count', 0)}",
        f"- {t('label_bookmark_added')}: "
        + ", ".join(display_timestamp(value) for value in record.get("bookmark_add_dates", []))
        if record.get("bookmark_add_dates")
        else f"- {t('label_bookmark_added')}: {t('none')}",
        f"- {t('label_tags')}: {render_tags(tags)}",
        "",
        f"## {t('section_category_paths')}",
        "",
        render_bulleted_paths(category_paths).rstrip(),
        "",
        f"## {t('section_purpose')}",
        "",
        description,
        "",
        f"## {t('section_note')}",
        "",
        note,
    ]
    if titles:
        lines.extend(
            [
                "",
                f"## {t('label_also_seen_as')}",
                "",
                "\n".join(f"- {value}" for value in titles),
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_links_index(records: Dict[str, Dict[str, object]], note_paths: Dict[str, Path]) -> str:
    lines = [
        f"# {t('links_title')}",
        "",
        f"- {t('label_counts')}: {len(records)}",
        "",
        f"## {t('section_all_links')}",
        "",
    ]
    if not records:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"
    for record in sort_records(records.values()):
        lines.append(
            render_link_summary_line(
                record,
                heading_level=3,
                from_file=ROOT_LINKS / "Index.md",
                note_path=note_paths[str(record["url"])],
            )
        )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_links_root_compact(shards: Dict[str, List[Dict[str, object]]]) -> str:
    lines = [
        f"# {t('links_title')}",
        "",
        f"- {t('label_counts')}: {sum(len(records) for records in shards.values())}",
        "",
        f"## {t('section_shards')}",
        "",
    ]
    if not shards:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"
    index_path = ROOT_LINKS / "Index.md"
    for key in sorted(shards, key=shard_sort_key):
        rel = markdown_rel_path(index_path, link_shard_rel_path(key))
        lines.append(f"- [{shard_display_name(key)}]({rel}) ({len(shards[key])})")
    return "\n".join(lines).rstrip() + "\n"


def render_links_root_compact_with_heavy_hosts(
    general_shards: Dict[str, List[Dict[str, object]]],
    heavy_host_shards: Dict[str, Dict[str, List[Dict[str, object]]]],
) -> str:
    total = sum(len(items) for items in general_shards.values()) + sum(
        sum(len(records) for records in subshards.values()) for subshards in heavy_host_shards.values()
    )
    lines = [
        f"# {t('links_title')}",
        "",
        f"- {t('label_counts')}: {total}",
        "",
    ]
    index_path = ROOT_LINKS / "Index.md"
    if heavy_host_shards:
        lines.extend([f"## Heavy Hosts", ""])
        for host in sorted(heavy_host_shards, key=str.lower):
            rel = markdown_rel_path(index_path, heavy_host_dir_rel_path(host) / "Index.md")
            host_total = sum(len(records) for records in heavy_host_shards[host].values())
            lines.append(f"- [`{host}`]({rel}) ({host_total})")
        lines.append("")
    lines.extend([f"## {t('section_shards')}", ""])
    if not general_shards and not heavy_host_shards:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"
    for key in sorted(general_shards, key=shard_sort_key):
        rel = markdown_rel_path(index_path, link_shard_rel_path(key))
        lines.append(f"- [{shard_display_name(key)}]({rel}) ({len(general_shards[key])})")
    return "\n".join(lines).rstrip() + "\n"


def render_link_shard_compact(shard_key: str, records: List[Dict[str, object]]) -> str:
    lines = [
        f"# {t('links_title')} / {shard_display_name(shard_key)}",
        "",
        f"- {t('label_counts')}: {len(records)}",
        "",
    ]
    if not records:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"

    host_groups: DefaultDict[str, List[Dict[str, object]]] = defaultdict(list)
    for record in records:
        host_groups[str(record.get("host", "unknown-host"))].append(record)

    for host in sorted(host_groups, key=str.lower):
        lines.extend([f"## `{host}`", ""])
        for record in host_groups[host]:
            lines.append(render_link_summary_line(record, heading_level=3))
            lines.append("")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_heavy_host_index(host: str, subshards: Dict[str, List[Dict[str, object]]]) -> str:
    lines = [
        f"# {t('links_title')} / `{host}`",
        "",
        f"- {t('label_counts')}: {sum(len(records) for records in subshards.values())}",
        "",
        f"## {t('section_shards')}",
        "",
    ]
    index_path = heavy_host_dir_rel_path(host) / "Index.md"
    for key in sorted(subshards, key=shard_sort_key):
        rel = markdown_rel_path(index_path, heavy_host_shard_rel_path(host, key))
        lines.append(f"- [{shard_display_name(key)}]({rel}) ({len(subshards[key])})")
    return "\n".join(lines).rstrip() + "\n"


def render_heavy_host_shard(host: str, shard_key: str, records: List[Dict[str, object]]) -> str:
    lines = [
        f"# {t('links_title')} / `{host}` / {shard_display_name(shard_key)}",
        "",
        f"- {t('label_counts')}: {len(records)}",
        "",
    ]
    if not records:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"
    for record in records:
        lines.append(render_link_summary_line(record, heading_level=2))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_domain_index(
    host: str,
    records: List[Dict[str, object]],
    note_paths: Dict[str, Path],
    output_path: Path,
) -> str:
    lines = [
        f"# `{host}`",
        "",
        f"- {t('label_counts')}: {len(records)}",
        "",
        f"## {t('section_domain_links')}",
        "",
    ]
    if not records:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"
    for record in sort_records(records):
        lines.append(
            render_link_summary_line(
                record,
                heading_level=3,
                from_file=output_path,
                note_path=note_paths[str(record["url"])],
            )
        )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_domains_root(
    groups: Dict[str, List[Dict[str, object]]],
    domain_paths: Dict[str, Path],
) -> str:
    lines = [
        f"# {t('domains_title')}",
        "",
        f"- {t('label_counts')}: {len(groups)}",
        "",
        f"## {t('section_links')}",
        "",
    ]
    if not groups:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"
    index_path = ROOT_DOMAINS / "Index.md"
    for host in sorted(groups, key=str.lower):
        rel = markdown_rel_path(index_path, domain_paths[host])
        lines.append(f"- [`{host}`]({rel}) ({len(groups[host])})")
    return "\n".join(lines).rstrip() + "\n"


def render_domains_root_compact(shards: Dict[str, List[Tuple[str, List[Dict[str, object]]]]]) -> str:
    lines = [
        f"# {t('domains_title')}",
        "",
        f"- {t('label_counts')}: {sum(len(items) for items in shards.values())}",
        "",
        f"## {t('section_shards')}",
        "",
    ]
    if not shards:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"
    index_path = ROOT_DOMAINS / "Index.md"
    for key in sorted(shards, key=shard_sort_key):
        rel = markdown_rel_path(index_path, domain_shard_rel_path(key))
        lines.append(f"- [{shard_display_name(key)}]({rel}) ({len(shards[key])})")
    return "\n".join(lines).rstrip() + "\n"


def render_domain_shard_compact(
    shard_key: str,
    host_records: List[Tuple[str, List[Dict[str, object]]]],
) -> str:
    lines = [
        f"# {t('domains_title')} / {shard_display_name(shard_key)}",
        "",
        f"- {t('label_counts')}: {len(host_records)}",
        "",
    ]
    if not host_records:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"

    for host, records in host_records:
        lines.extend([f"## `{host}`", ""])
        lines.append(f"- {t('label_counts')}: {len(records)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_categories_root_compact(
    summary_root: Tuple[str, ...],
    top_keys: Sequence[Tuple[str, ...]],
    folder_all_urls: DefaultDict[Tuple[str, ...], Set[str]],
) -> str:
    lines = [
        f"# {t('categories_title')}",
        "",
        f"- {t('label_summary_root')}: {display_category_path(summary_root)}",
        f"- {t('label_counts')}: {len(folder_all_urls.get(summary_root, set()))}",
        "",
        f"## {t('section_subcategories')}",
        "",
    ]
    if not top_keys:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"
    index_path = ROOT_CATEGORIES / "Index.md"
    for top_key in top_keys:
        rel = markdown_rel_path(index_path, compact_top_category_rel_dir(top_key) / "Index.md")
        lines.append(f"- [{top_key[-1]}]({rel}) ({len(folder_all_urls.get(top_key, set()))})")
    return "\n".join(lines).rstrip() + "\n"


def render_compact_category_node(
    category_key: Tuple[str, ...],
    folder_children: DefaultDict[Tuple[str, ...], Set[str]],
    folder_direct_links: DefaultDict[Tuple[str, ...], List[Dict[str, object]]],
    lines: List[str],
    heading_level: int,
) -> None:
    level = max(2, min(6, heading_level))
    lines.extend([f"{'#' * level} {category_key[-1]}", ""])
    direct_links = sort_records(folder_direct_links.get(category_key, []))
    for record in direct_links:
        lines.append(
            render_link_summary_line(
                record,
                heading_level=min(level + 1, 6),
                include_domain=True,
                include_categories=False,
            )
        )
        lines.append("")
    for child in sorted(folder_children.get(category_key, set()), key=lambda value: value.lower()):
        render_compact_category_node(
            category_key + (child,),
            folder_children,
            folder_direct_links,
            lines,
            heading_level=min(level + 1, 6),
        )


def render_compact_category_branch_note(
    branch_key: Tuple[str, ...],
    folder_children: DefaultDict[Tuple[str, ...], Set[str]],
    folder_direct_links: DefaultDict[Tuple[str, ...], List[Dict[str, object]]],
    folder_all_urls: DefaultDict[Tuple[str, ...], Set[str]],
) -> str:
    lines = [
        f"# {display_category_path(branch_key)}",
        "",
        f"- {t('label_counts')}: {len(folder_all_urls.get(branch_key, set()))}",
        "",
    ]
    direct_links = sort_records(folder_direct_links.get(branch_key, []))
    if direct_links:
        lines.extend([f"## {t('section_direct_links')}", ""])
        for record in direct_links:
            lines.append(
                render_link_summary_line(
                    record,
                    heading_level=3,
                    include_domain=True,
                    include_categories=False,
                )
            )
            lines.append("")
    for child in sorted(folder_children.get(branch_key, set()), key=lambda value: value.lower()):
        render_compact_category_node(
            branch_key + (child,),
            folder_children,
            folder_direct_links,
            lines,
            heading_level=2,
        )
    if len(lines) <= 4:
        lines.append(t("empty_report"))
    return "\n".join(lines).rstrip() + "\n"


def render_compact_top_category_index(
    top_key: Tuple[str, ...],
    branch_keys: Sequence[Tuple[str, ...]],
    folder_all_urls: DefaultDict[Tuple[str, ...], Set[str]],
) -> str:
    lines = [
        f"# {display_category_path(top_key)}",
        "",
        f"- {t('label_counts')}: {len(folder_all_urls.get(top_key, set()))}",
        "",
        f"## {t('section_subcategories')}",
        "",
    ]
    index_path = compact_top_category_rel_dir(top_key) / "Index.md"
    if not branch_keys:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"
    for branch_key in sorted(branch_keys, key=lambda item: (len(item), [part.lower() for part in item])):
        rel = markdown_rel_path(index_path, compact_branch_note_rel_path(branch_key))
        label = branch_key[-1] if len(branch_key) > len(top_key) else t("section_summary")
        lines.append(f"- [{label}]({rel}) ({len(folder_all_urls.get(branch_key, set()))})")
    return "\n".join(lines).rstrip() + "\n"


def render_category_index(
    category_key: Tuple[str, ...],
    folder_children: DefaultDict[Tuple[str, ...], Set[str]],
    folder_direct_links: DefaultDict[Tuple[str, ...], List[Dict[str, object]]],
    folder_all_urls: DefaultDict[Tuple[str, ...], Set[str]],
    category_paths: Dict[Tuple[str, ...], Path],
    note_paths: Optional[Dict[str, Path]] = None,
) -> str:
    current_path = category_paths[category_key] / "Index.md"
    title = display_category_path(category_key)
    lines = [
        f"# {title}",
        "",
        f"- {t('label_counts')}: {len(folder_all_urls.get(category_key, set()))}",
        "",
    ]

    child_names = sorted(folder_children.get(category_key, set()), key=lambda value: value.lower())
    if child_names:
        lines.extend([f"## {t('section_subcategories')}", ""])
        for child in child_names:
            child_key = category_key + (child,)
            child_path = category_paths[child_key] / "Index.md"
            rel = markdown_rel_path(current_path, child_path)
            count = len(folder_all_urls.get(child_key, set()))
            lines.append(f"- [{child}]({rel}) ({count})")
        lines.append("")

    direct_links = sort_records(folder_direct_links.get(category_key, []))
    if direct_links:
        heading = t("section_direct_links") if category_key else t("section_root_links")
        lines.extend([f"## {heading}", ""])
        for record in direct_links:
            note_path = note_paths[str(record["url"])] if note_paths else None
            lines.append(
                render_link_summary_line(
                    record,
                    heading_level=3,
                    from_file=current_path if note_path else None,
                    note_path=note_path,
                )
            )
            lines.append("")
        lines.append("")

    if not child_names and not direct_links:
        lines.append(t("empty_report"))
    return "\n".join(lines).rstrip() + "\n"


def render_change_report(
    title: str,
    urls: Sequence[str],
    state: Dict[str, object],
    note_paths: Optional[Dict[str, Path]],
    output_path: Path,
) -> str:
    records_map = state.get("records", {})
    if not isinstance(records_map, dict):
        records_map = {}
    lines = [f"# {title}", ""]
    if not urls:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"
    lines.append(f"- {t('label_counts')}: {len(urls)}")
    lines.append("")
    for url in urls:
        record = records_map.get(url)
        if not isinstance(record, dict):
            continue
        title_text = str(record.get("title", url))
        description = clean_text(str(record.get("description", ""))) or t("pending_description")
        categories = "; ".join(display_category_path(parts) for parts in record.get("category_paths", [[]]))
        lines.append(f"## {title_text}")
        lines.append("")
        lines.append(f"- {t('label_url')}: [{url}]({url})")
        lines.append(f"- {t('label_domain')}: `{record.get('host', '')}`")
        lines.append(f"- {t('label_categories_short')}: {categories}")
        lines.append(f"- {t('section_purpose')}: {description}")
        if record.get("status") == "active" and note_paths:
            rel = markdown_rel_path(output_path, note_paths[url])
            lines.append(f"- {t('links_title')}: [{title_text}]({rel})")
        else:
            lines.append(f"- {t('label_status')}: {t('status_removed' if record.get('status') == 'removed' else 'status_active')}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_excluded_report(records: Dict[str, Dict[str, object]]) -> str:
    lines = [f"# {t('excluded_links_title')}", ""]
    if not records:
        lines.append(t("empty_report"))
        return "\n".join(lines) + "\n"
    lines.append(f"- {t('label_counts')}: {len(records)}")
    lines.append("")
    for record in sort_records(records.values()):
        title_text = str(record.get("title", record.get("url", "")))
        categories = "; ".join(display_category_path(parts) for parts in record.get("category_paths", [[]]))
        reasons = ", ".join(str(item) for item in record.get("filter_reasons", [])) or t("none")
        lines.append(f"## {title_text}")
        lines.append("")
        lines.append(f"- {t('label_url')}: [{record.get('url', '')}]({record.get('url', '')})")
        lines.append(f"- {t('label_domain')}: `{record.get('host', '')}`")
        lines.append(f"- {t('label_categories_short')}: {categories}")
        lines.append(f"- {t('section_note')}: `{reasons}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_dashboard(
    entries_count: int,
    unique_count: int,
    target_root: Path,
    active: Dict[str, Dict[str, object]],
    folder_all_urls: DefaultDict[Tuple[str, ...], Set[str]],
    domain_groups: Dict[str, List[Dict[str, object]]],
    changes: Dict[str, List[str]],
    pending_annotations: List[Dict[str, object]],
    excluded_records: Dict[str, Dict[str, object]],
    source_html: Path,
    state: Dict[str, object],
    state_root: Path,
    layout: str,
    summary_root: Tuple[str, ...],
    principal_category_items: Sequence[Dict[str, object]],
) -> str:
    lines = [
        f"# {t('dashboard_title')}",
        "",
        f"## {t('stats_title')}",
        "",
        f"- {t('label_total_bookmarks')}: {entries_count}",
        f"- {t('label_total_unique')}: {unique_count}",
        f"- {t('label_active')}: {len(active)}",
        f"- {t('label_categories')}: {max(len(folder_all_urls) - 1, 0)}",
        f"- {t('label_domains')}: {len(domain_groups)}",
        f"- {t('label_new')}: {len(changes['new'])}",
        f"- {t('label_changed')}: {len(changes['changed'])}",
        f"- {t('label_removed')}: {len(changes['removed'])}",
        f"- {t('label_excluded')}: {len(excluded_records)}",
        f"- {t('label_pending')}: {len(pending_annotations)}",
        f"- {t('label_layout')}: `{layout}`",
        f"- {t('label_state_root')}: `{state_root}`",
        f"- {t('label_last_sync')}: {state.get('last_sync_at', '')}",
        f"- {t('label_source_html')}: {source_html}",
        "",
        f"## {t('section_principal_categories')}",
        "",
        f"- {t('label_summary_root')}: {display_category_path(summary_root)}",
        "",
    ]
    if principal_category_items:
        for item in principal_category_items:
            lines.append(f"- {item['name']} ({item['count']})")
    else:
        lines.append(f"- {t('empty_report')}")
    lines.extend(
        [
            "",
            f"## {t('section_recent_changes')}",
            "",
            f"- [{t('new_links_title')}]({(ROOT_REPORTS / NEW_LINKS_FILE).as_posix()})",
            f"- [{t('changed_links_title')}]({(ROOT_REPORTS / CHANGED_LINKS_FILE).as_posix()})",
            f"- [{t('removed_links_title')}]({(ROOT_REPORTS / REMOVED_LINKS_FILE).as_posix()})",
            f"- [{t('excluded_links_title')}]({(ROOT_REPORTS / EXCLUDED_LINKS_FILE).as_posix()})",
            "",
            f"## {t('section_links')}",
            "",
            f"- [{t('categories_title')}]({(ROOT_CATEGORIES / 'Index.md').as_posix()})",
            f"- [{t('links_title')}]({(ROOT_LINKS / 'Index.md').as_posix()})",
            f"- [{t('domains_title')}]({(ROOT_DOMAINS / 'Index.md').as_posix()})",
            "",
            f"## {t('section_annotations')}",
            "",
        ]
    )
    if pending_annotations:
        lines.append(f"- {t('summary_show_pending')}: `{state_root / PENDING_ANNOTATIONS_FILE}`")
    else:
        lines.append(f"- {t('summary_all_good')}")
    return "\n".join(lines).rstrip() + "\n"


def remove_path(path: Path) -> None:
    if not path.exists():
        return
    if path.is_symlink() or path.is_file():
        path.unlink()
        return
    shutil.rmtree(path)


def sync_path_in_place(source: Path, target: Path) -> None:
    if source.is_dir():
        if target.exists() and not target.is_dir():
            remove_path(target)
        target.mkdir(parents=True, exist_ok=True)
        source_names = {child.name for child in source.iterdir()}
        target_names = {child.name for child in target.iterdir()}
        for stale_name in sorted(target_names - source_names):
            remove_path(target / stale_name)
        for child in source.iterdir():
            sync_path_in_place(child, target / child.name)
        return

    if target.exists() and target.is_dir():
        remove_path(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    temp_target = target.parent / f".{target.name}.codex-tmp"
    if temp_target.exists():
        remove_path(temp_target)
    shutil.copy2(source, temp_target)
    os.replace(temp_target, target)


def replace_target(target_root: Path, stage_root: Path) -> None:
    target_root.mkdir(parents=True, exist_ok=True)
    stage_names = {child.name for child in stage_root.iterdir()}
    for managed_name in sorted(MANAGED_TOP_LEVEL_NAMES):
        source = stage_root / managed_name
        target = target_root / managed_name
        if source.exists():
            sync_path_in_place(source, target)
        elif target.exists():
            remove_path(target)


def is_within(path: Path, parent: Path) -> bool:
    try:
        path.resolve().relative_to(parent.resolve())
        return True
    except ValueError:
        return False


def stash_state_root_extras(state_root: Path, stash_root: Path) -> None:
    core_entries = {
        STATE_FILE,
        PENDING_ANNOTATIONS_FILE,
        EXCLUDED_LINKS_JSON,
        LATEST_SUMMARY_FILE,
        "rendered",
    }
    if not state_root.exists():
        return
    stash_root.mkdir(parents=True, exist_ok=True)
    for child in state_root.iterdir():
        if child.name in core_entries:
            continue
        destination = stash_root / child.name
        if child.is_dir():
            shutil.copytree(child, destination, dirs_exist_ok=True)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(child, destination)


def restore_state_root_extras(state_root: Path, stash_root: Path) -> None:
    if not stash_root.exists():
        return
    for child in stash_root.iterdir():
        destination = state_root / child.name
        if child.is_dir():
            shutil.copytree(child, destination, dirs_exist_ok=True)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(child, destination)


def cleanup_known_conflict_copies(target_root: Path) -> None:
    managed_prefixes = {
        ROOT_REPORTS.name,
        ROOT_CATEGORIES.name,
        ROOT_LINKS.name,
        ROOT_DOMAINS.name,
        "00Reports",
        "Dashboard",
    }
    if not target_root.exists():
        return
    for path in target_root.iterdir():
        name = path.name
        if name in MANAGED_TOP_LEVEL_NAMES or name in {"_state", ROOT_STATE.name}:
            continue
        if not any(name == prefix or name.startswith(f"{prefix} ") for prefix in managed_prefixes):
            continue
        remove_path(path)


def expected_top_level_names(state_root: Path, target_root: Path) -> Set[str]:
    names = set(MANAGED_TOP_LEVEL_NAMES)
    if is_within(state_root, target_root):
        names.add(state_root.name)
    return names


def archive_structure_report(target_root: Path, state_root: Path) -> Dict[str, object]:
    expected_names = expected_top_level_names(state_root, target_root)
    report: Dict[str, object] = {
        "target_root": str(target_root),
        "state_root": str(state_root),
        "expected_top_level": sorted(expected_names),
        "top_level_entries": [],
        "missing_top_level": [],
        "unexpected_top_level": [],
        "conflict_copies": [],
        "missing_state_files": [],
        "ok": True,
    }

    if not target_root.exists():
        report["missing_top_level"] = sorted(expected_names)
        report["ok"] = False
        return report

    top_level_entries = sorted(path.name for path in target_root.iterdir())
    report["top_level_entries"] = top_level_entries
    report["missing_top_level"] = sorted(name for name in expected_names if not (target_root / name).exists())
    report["unexpected_top_level"] = sorted(name for name in top_level_entries if name not in expected_names)

    managed_prefixes = {
        ROOT_REPORTS.name,
        ROOT_CATEGORIES.name,
        ROOT_LINKS.name,
        ROOT_DOMAINS.name,
        "Dashboard",
    }
    conflict_copies = []
    for name in top_level_entries:
        if name in expected_names:
            continue
        if any(name == prefix or name.startswith(f"{prefix} ") for prefix in managed_prefixes):
            conflict_copies.append(name)
    report["conflict_copies"] = sorted(conflict_copies)

    required_state_files = [
        STATE_FILE,
        LATEST_SUMMARY_FILE,
        PENDING_ANNOTATIONS_FILE,
        EXCLUDED_LINKS_JSON,
    ]
    report["missing_state_files"] = sorted(
        filename for filename in required_state_files if not (state_root / filename).exists()
    )
    report["ok"] = not any(
        [
            report["missing_top_level"],
            report["unexpected_top_level"],
            report["conflict_copies"],
            report["missing_state_files"],
        ]
    )
    return report


def ensure_archive_structure(target_root: Path, state_root: Path) -> None:
    report = archive_structure_report(target_root, state_root)
    if report["ok"]:
        return
    raise RuntimeError(json.dumps(report, ensure_ascii=False, indent=2))


def build_summary(
    entries_count: int,
    unique_count: int,
    target_root: Path,
    state_root: Path,
    changes: Dict[str, List[str]],
    active: Dict[str, Dict[str, object]],
    pending_annotations: List[Dict[str, object]],
    excluded_records: Dict[str, Dict[str, object]],
    folder_all_urls: DefaultDict[Tuple[str, ...], Set[str]],
    domain_groups: Dict[str, List[Dict[str, object]]],
    source_html: Path,
    layout: str,
    summary_root: Tuple[str, ...],
    principal_category_items: Sequence[Dict[str, object]],
    rendered_files: int,
    rendered_dirs: int,
) -> Dict[str, object]:
    sample_limit = 20
    return {
        "container_root": str(target_root),
        "source_html": str(source_html),
        "bookmark_entries_in_html": entries_count,
        "unique_urls_in_html": unique_count,
        "active_urls": len(active),
        "category_nodes": max(len(folder_all_urls) - 1, 0),
        "domains": len(domain_groups),
        "new_urls": len(changes["new"]),
        "changed_urls": len(changes["changed"]),
        "removed_urls": len(changes["removed"]),
        "reactivated_urls": len(changes["reactivated"]),
        "excluded_noise_urls": len(excluded_records),
        "pending_annotations": len(pending_annotations),
        "layout": layout,
        "rendered_files": rendered_files,
        "rendered_dirs": rendered_dirs,
        "state_root": str(state_root),
        "summary_root_path": list(summary_root),
        "principal_categories": list(principal_category_items),
        "sample_limit": sample_limit,
        "new_url_sample": changes["new"][:sample_limit],
        "changed_url_sample": changes["changed"][:sample_limit],
        "removed_url_sample": changes["removed"][:sample_limit],
        "excluded_url_sample": list(sorted(excluded_records))[:sample_limit],
        "pending_annotations_path": str(state_root / PENDING_ANNOTATIONS_FILE),
        "excluded_links_path": str(target_root / ROOT_REPORTS / EXCLUDED_LINKS_FILE),
        "excluded_links_json_path": str(state_root / EXCLUDED_LINKS_JSON),
        "latest_summary_path": str(state_root / LATEST_SUMMARY_FILE),
        "reports": {
            "dashboard": str(target_root / DASHBOARD_FILE),
            "new_links": str(target_root / ROOT_REPORTS / NEW_LINKS_FILE),
            "changed_links": str(target_root / ROOT_REPORTS / CHANGED_LINKS_FILE),
            "removed_links": str(target_root / ROOT_REPORTS / REMOVED_LINKS_FILE),
            "excluded_links": str(target_root / ROOT_REPORTS / EXCLUDED_LINKS_FILE),
            "categories_index": str(target_root / ROOT_CATEGORIES / "Index.md"),
            "links_index": str(target_root / ROOT_LINKS / "Index.md"),
            "domains_index": str(target_root / ROOT_DOMAINS / "Index.md"),
        },
    }


def render_archive(
    target_root: Path,
    state_root: Path,
    raw_entries: Sequence[BookmarkEntry],
    current_records: Dict[str, Dict[str, object]],
    excluded_records: Dict[str, Dict[str, object]],
    state: Dict[str, object],
    changes: Dict[str, List[str]],
    pending_annotations: List[Dict[str, object]],
    source_html: Path,
    layout: str,
) -> Dict[str, object]:
    active = active_records(state)
    folder_children, folder_direct_links, folder_all_urls = build_category_tree(active)
    category_paths = build_category_fs_map(folder_children)
    note_paths = {url: link_note_rel_path(record) for url, record in active.items()} if layout == "per-url" else {}
    summary_root = collapse_summary_root(folder_children)
    principal_category_items = principal_categories(summary_root, folder_children, folder_all_urls)

    domain_groups: DefaultDict[str, List[Dict[str, object]]] = defaultdict(list)
    for record in active.values():
        domain_groups[str(record.get("host", "unknown-host"))].append(record)
    domain_paths = {host: domain_note_rel_path(host) for host in domain_groups} if layout == "per-url" else {}
    link_shards, heavy_host_shards = build_link_shards(active) if layout == "compact" else ({}, {})
    domain_shards = build_domain_shards(domain_groups) if layout == "compact" else {}

    with tempfile.TemporaryDirectory(prefix="bookmark-sync-") as temp_dir:
        stage_root = Path(temp_dir) / target_root.name
        state_extras_stash = Path(temp_dir) / "state-extras"
        stage_root.mkdir(parents=True, exist_ok=True)

        if layout == "per-url":
            for record in active.values():
                rel = note_paths[str(record["url"])]
                path = stage_root / rel
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(render_link_note(record), encoding="utf-8")

            links_index_path = stage_root / ROOT_LINKS / "Index.md"
            links_index_path.parent.mkdir(parents=True, exist_ok=True)
            links_index_path.write_text(render_links_index(active, note_paths), encoding="utf-8")
        else:
            links_index_path = stage_root / ROOT_LINKS / "Index.md"
            links_index_path.parent.mkdir(parents=True, exist_ok=True)
            links_index_path.write_text(
                render_links_root_compact_with_heavy_hosts(link_shards, heavy_host_shards),
                encoding="utf-8",
            )
            for shard_key, records in link_shards.items():
                shard_path = stage_root / link_shard_rel_path(shard_key)
                shard_path.parent.mkdir(parents=True, exist_ok=True)
                shard_path.write_text(render_link_shard_compact(shard_key, records), encoding="utf-8")
            for host, subshards in heavy_host_shards.items():
                host_dir = stage_root / heavy_host_dir_rel_path(host)
                host_dir.mkdir(parents=True, exist_ok=True)
                (host_dir / "Index.md").write_text(render_heavy_host_index(host, subshards), encoding="utf-8")
                for shard_key, records in subshards.items():
                    shard_path = stage_root / heavy_host_shard_rel_path(host, shard_key)
                    shard_path.parent.mkdir(parents=True, exist_ok=True)
                    shard_path.write_text(render_heavy_host_shard(host, shard_key, records), encoding="utf-8")

        if layout == "per-url":
            for category_key, rel_dir in category_paths.items():
                output_path = stage_root / rel_dir / "Index.md"
                output_path.parent.mkdir(parents=True, exist_ok=True)
                output_path.write_text(
                    render_category_index(
                        category_key,
                        folder_children,
                        folder_direct_links,
                        folder_all_urls,
                        category_paths,
                        note_paths if layout == "per-url" else None,
                    ),
                    encoding="utf-8",
                )
        else:
            branches_by_top = collect_compact_category_branches(active, summary_root)
            top_keys = sorted(branches_by_top, key=lambda item: item[-1].lower())
            categories_index_path = stage_root / ROOT_CATEGORIES / "Index.md"
            categories_index_path.parent.mkdir(parents=True, exist_ok=True)
            categories_index_path.write_text(
                render_categories_root_compact(summary_root, top_keys, folder_all_urls),
                encoding="utf-8",
            )
            for top_key in top_keys:
                top_dir = stage_root / compact_top_category_rel_dir(top_key)
                top_dir.mkdir(parents=True, exist_ok=True)
                (top_dir / "Index.md").write_text(
                    render_compact_top_category_index(
                        top_key,
                        sorted(branches_by_top[top_key], key=lambda item: (len(item), [part.lower() for part in item])),
                        folder_all_urls,
                    ),
                    encoding="utf-8",
                )
                for branch_key in branches_by_top[top_key]:
                    branch_path = stage_root / compact_branch_note_rel_path(branch_key)
                    branch_path.parent.mkdir(parents=True, exist_ok=True)
                    branch_path.write_text(
                        render_compact_category_branch_note(
                            branch_key,
                            folder_children,
                            folder_direct_links,
                            folder_all_urls,
                        ),
                        encoding="utf-8",
                    )

        domains_root_path = stage_root / ROOT_DOMAINS / "Index.md"
        if layout == "per-url":
            domains_root_path.parent.mkdir(parents=True, exist_ok=True)
            domains_root_path.write_text(render_domains_root(domain_groups, domain_paths), encoding="utf-8")
            for host, records in domain_groups.items():
                output_path = stage_root / domain_paths[host]
                output_path.parent.mkdir(parents=True, exist_ok=True)
                output_path.write_text(
                    render_domain_index(host, records, note_paths, domain_paths[host]),
                    encoding="utf-8",
                )
        else:
            domains_root_path = stage_root / ROOT_DOMAINS / "Index.md"
            domains_root_path.parent.mkdir(parents=True, exist_ok=True)
            domains_root_path.write_text(render_domains_root_compact(domain_shards), encoding="utf-8")
            for shard_key, host_records in domain_shards.items():
                shard_path = stage_root / domain_shard_rel_path(shard_key)
                shard_path.parent.mkdir(parents=True, exist_ok=True)
                shard_path.write_text(
                    render_domain_shard_compact(shard_key, host_records),
                    encoding="utf-8",
                )

        reports_dir = stage_root / ROOT_REPORTS
        reports_dir.mkdir(parents=True, exist_ok=True)

        (reports_dir / NEW_LINKS_FILE).write_text(
            render_change_report(
                t("new_links_title"),
                changes["new"],
                state,
                note_paths if layout == "per-url" else None,
                ROOT_REPORTS / NEW_LINKS_FILE,
            ),
            encoding="utf-8",
        )
        (reports_dir / CHANGED_LINKS_FILE).write_text(
            render_change_report(
                t("changed_links_title"),
                changes["changed"],
                state,
                note_paths if layout == "per-url" else None,
                ROOT_REPORTS / CHANGED_LINKS_FILE,
            ),
            encoding="utf-8",
        )
        (reports_dir / REMOVED_LINKS_FILE).write_text(
            render_change_report(
                t("removed_links_title"),
                changes["removed"],
                state,
                note_paths if layout == "per-url" else None,
                ROOT_REPORTS / REMOVED_LINKS_FILE,
            ),
            encoding="utf-8",
        )
        (reports_dir / EXCLUDED_LINKS_FILE).write_text(render_excluded_report(excluded_records), encoding="utf-8")

        dashboard_text = render_dashboard(
            entries_count=len(raw_entries),
            unique_count=len(current_records),
            target_root=target_root,
            active=active,
            folder_all_urls=folder_all_urls,
            domain_groups=domain_groups,
            changes=changes,
            pending_annotations=pending_annotations,
            excluded_records=excluded_records,
            source_html=source_html,
            state=state,
            state_root=state_root,
            layout=layout,
            summary_root=summary_root,
            principal_category_items=principal_category_items,
        )
        (stage_root / DASHBOARD_FILE).write_text(dashboard_text, encoding="utf-8")

        rendered_files = sum(1 for path in stage_root.rglob("*") if path.is_file())
        rendered_dirs = sum(1 for path in stage_root.rglob("*") if path.is_dir())

        summary = build_summary(
            entries_count=len(raw_entries),
            unique_count=len(current_records),
            target_root=target_root,
            state_root=state_root,
            changes=changes,
            active=active,
            pending_annotations=pending_annotations,
            excluded_records=excluded_records,
            folder_all_urls=folder_all_urls,
            domain_groups=domain_groups,
            source_html=source_html,
            layout=layout,
            summary_root=summary_root,
            principal_category_items=principal_category_items,
            rendered_files=rendered_files,
            rendered_dirs=rendered_dirs,
        )
        if is_within(state_root, target_root):
            stash_state_root_extras(state_root, state_extras_stash)
        cleanup_known_conflict_copies(target_root)
        replace_target(target_root, stage_root)
        cleanup_known_conflict_copies(target_root)
        restore_state_root_extras(state_root, state_extras_stash)

    save_json(state_root / STATE_FILE, state)
    save_json(state_root / PENDING_ANNOTATIONS_FILE, pending_annotations)
    save_json(state_root / EXCLUDED_LINKS_JSON, excluded_records)
    save_json(state_root / LATEST_SUMMARY_FILE, summary)
    cleanup_known_conflict_copies(target_root)
    obsolete_render_root = state_root / "rendered"
    if obsolete_render_root.exists():
        shutil.rmtree(obsolete_render_root)
    ensure_archive_structure(target_root, state_root)

    return summary


def main() -> None:
    args = parse_args()
    set_active_language(args.title_language)

    source_html = Path(args.input_html).expanduser().resolve()
    target_root = Path(args.target_root).expanduser().resolve() / args.container_name
    if args.state_root:
        state_root = Path(args.state_root).expanduser().resolve()
    elif args.layout == "compact":
        state_root = default_external_state_root(target_root)
    else:
        state_root = target_root / ROOT_STATE
    annotations_file = Path(args.annotations_file).expanduser().resolve() if args.annotations_file else None

    if not source_html.exists():
        raise FileNotFoundError(f"input HTML not found: {source_html}")

    entries = parse_bookmark_html(source_html)
    clean_entries, excluded_entries = split_noise_entries(entries)
    current_records = aggregate_entries(clean_entries)
    excluded_records = aggregate_excluded_entries(excluded_entries)

    previous_state_path = state_root / STATE_FILE
    previous_state = load_state(previous_state_path) if args.mode == "merge" else {"version": STATE_VERSION, "records": {}}
    annotations = load_annotations(annotations_file)
    state, changes = merge_records(
        current_records,
        previous_state,
        annotations,
        source_html,
        args.mode,
        args.missing_policy,
    )
    pending_annotations = build_pending_annotations(state["records"])
    summary = render_archive(
        target_root=target_root,
        state_root=state_root,
        raw_entries=entries,
        current_records=current_records,
        excluded_records=excluded_records,
        state=state,
        changes=changes,
        pending_annotations=pending_annotations,
        source_html=source_html,
        layout=args.layout,
    )

    if args.summary_path:
        summary_path = Path(args.summary_path).expanduser().resolve()
        save_json(summary_path, summary)

    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
